[package]
name = "dvault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
serde = { workspace = true }
candid = { workspace = true }
ic-cdk = { version = "0.17.0", features = [], default-features = false }
